# Application Metadata
app:
  name: Virtual Stage Academy
  version: 1.0
  environment: development  # Change to 'production' or 'preview' when needed

# Zoom Configuration
zoom:
  redirect_uri: http://localhost:5000/callback  # Local development
  # Uncomment and update when deploying to production
  # redirect_uri: https://overlays.virtualstageacademy.io/oauth/callback
  DEV_WEBSOCKET_URL: wss://ws.zoom.us/ws?subscriptionId=LAUx-VqaTvOv70nUu6ru2A

# WebSocket Configuration
websocket:
  development:
    url: ${DEV_WEBSOCKET_URL}  # Dynamically replaced from .env
  preview:
    url: ${PREVIEW_WEBSOCKET_URL}  # Dynamically replaced from .env
  production:
    url: ${PROD_WEBSOCKET_URL}  # Dynamically replaced from .env

# Overlay Settings
overlays:
  default_style:
    font: "Arial"
    color: "#FFFFFF"
    size: 14
  positions:
    chat_overlay:
      x: 50
      y: 50
    emoji_overlay:
      x: 300
      y: 100

# Logging and Debugging
logging:
  level: debug  # Options: debug, info, warning, error
  file: logs/vsa.log

# Feature Flags
features:
  enable_emoji_overlay: true
  enable_chat_moderation: false
