# Application Metadata
app:
  name: Virtual Stage Academy
  version: 1.0
  environment: development  # Possible values: development, production

# Zoom Configuration
zoom:
  redirect_uri: https://overlays.virtualstageacademy.io/oauth/callback
  webhook_endpoint: wss://ws.zoom.us/ws?subscriptionId=LAUx-VqaTvOv70nUu6ru2A
  scopes:
    - meeting:read
    - chat_message:read
    - chat_message:write
    - reaction:read
    - user:read

# Overlay Settings
overlays:
  default_style:
    font: "Arial"
    color: "#FFFFFF"
    size: 14
  positions:
    chat_overlay: 
      x: 50
      y: 50
    emoji_overlay: 
      x: 300
      y: 100

# Logging and Debugging
logging:
  level: debug  # Options: debug, info, warning, error
  file: logs/vsa.log

# Feature Flags
features:
  enable_emoji_overlay: true
  enable_chat_moderation: false

# Integration Settings
integrations:
  obs:
    stream_deck_integration: true
  google_analytics:
    tracking_id: UA-XXXXXX-X
